testApp/config/routes.rb
TestApp::Application.routes.draw do 
  get "showallemp/index"
 
  devise_for :members,:controllers => { :sessions => "ses" }
   get "viewallemployees/index"
   get "showallemp/index"
  get "welcome/index"
  get "users/admins_welcome"
  resources :projects

  resources :users

   

  

	root :to => 'welcome#index'
	

end

testApp/app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :end_date, :location, :name, :start_date, :user_id
	validates :name, presence: true, length: { maximum: 20 }, :format => { :with => /^[A-Za-z]+$/ } 
        validates :location, presence: true, length: { maximum: 20 }, :format => { :with => /^[A-Za-z]+$/ } 
	validates :user_id, presence: true, length: { maximum: 20 }, :format => { :with => /^[-0-9]+$/ } 
belongs_to :user
	


end

testApp/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json

  def index
    @projects = Project.order(:name)
    @projects = Project.paginate page: params[:page],
    per_page: 6
  
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    	flag = 0
	@user = User.all
	@user.each do |user|
		    if (user.id == @project.user_id)
			flag = 1
			break
		    end
	 end

    if flag==1
         respond_to do |format|
                    if @project.save
        		format.html { redirect_to @project, notice: 'Project was successfully created.' }
        		format.json { render json: @project, status: :created, location: @project }
      		    else
        		format.html { render action: "new" }
        		format.json { render json: @project.errors, status: :unprocessable_entity }
      		     end
         end
     else
         redirect_to new_project_path, notice: 'Emp-Id not available. Refer view all employees'
        
     end

  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
     @project = Project.find(params[:id])
 				
      @user=(User.where(id: params[:project][:user_id]))[0]

      pro_name=@user.project_name				
      #pro_id=@user.project_id
      #render text: pro_name

         respond_to do |format|
                    t=1
            if @project.update_attributes(params[:project])
                    if(@user.project_name=="none")				
	
 
                    	@user.update_attribute(:project_name,@project.name)
			@user.update_attribute(:project_id,@project.id)

         	     else
			arr=Array.new
			arr=pro_name.split(", ")

			arr.each do |i|
                 		if(i == @project.name)
				@user.update_attribute(:project_name,pro_name)
				@user.update_attribute(:project_id,pro_id)
				t=0
				break
                          
	        		 end
	  		end #end of aaray
         	    if t==1		

			 @user.update_attribute(:project_name,pro_name + ", " + @project.name)
         	     end		
             end
	
		
       		     format.html { redirect_to @project, notice: 'Project was successfully updated.' }
		     format.json { head :no_content }

             else
        	     format.html { render action: "edit" }
                     format.json { render json: @project.errors, status: :unprocessable_entity }
             end
    
    end

	
	#render text: @user.id

  #changes done here... repeated code removed

  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
	       @project = Project.find(params[:id])
	       @project.destroy

    respond_to do |format|
                format.html { redirect_to projects_url }
                format.json { head :no_content }
    end
  end

  
end

testApp/app/helpers/projects_helper.rb
module ProjectsHelper
end

testApp/app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul> 
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>&nbsp&nbsp&nbsp<%= link_to 'View all Employees', viewallemployees_index_path %> <br>

  </div>



  <div class="actions">
<br><br>
    <%= f.submit %>
  </div>
<% end %>

testApp/app/views/projects/edit.html.erb
<div id="sidepanel">
<br><br>
<%= link_to "View Projects",projects_path %>
<br><br><hr>

<br>
<%= link_to "View User",users_path %>
</div>
<div id="content">

<h1>Editing project</h1>

<%= render 'form' %>
<br><br>
<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

</div>

testApp/app/views/projects/index.html.erb
<div id="sidepanel">
<br><br>
<%= link_to "View Projects",projects_path %>
<br><br><hr>

<br>
<%= link_to "View User",users_path %>
</div>

<div id="notice"><%= notice %></div>

<div id="content">
<h1>Listing projects</h1>

<table style="border:1px solid black">
  <tr>
    <th style="border-bottom: 1px solid black">Name</th>
    <th style="border-bottom: 1px solid black">Start date</th>
    <th style="border-bottom: 1px solid black">End date</th>
    <th style="border-bottom: 1px solid black">Location</th>
    <th style="border-bottom: 1px solid black">Handled-By</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr style="border: 1px solid black">
    <td><%= project.name %></td>
    <td><%= project.start_date %></td>
    <td><%= project.end_date %></td>
    <td><%= project.location %></td>
    <td><%= project.user_id %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Assign', edit_project_path(project) %></td>
    <!--<td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
     
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>
<%= will_paginate @projects %></p> 
</div>

testApp/app/views/projects/new.html.erb
<div id="sidepanel">
<%#= link_to "View Projects",projects_path %>

<%#= link_to "View User",users_path %>
</div>



<div id="content">
<div id="notice"><%= notice %></div>
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

</div>

testApp/app/views/projects/show.html.erb
<div id="sidepanel">
<br><br>
<%= link_to "View Projects",projects_path %>
<br><br><hr>

<br>
<%= link_to "View User",users_path %>
</div>
<div id="content">

<p id="notice"><%= notice %></p>
<h2> Project id:   <%= @project.id %></h2>
<hr>
<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Start date:</b>
  <%= @project.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @project.end_date %>
</p>

<p>
  <b>User_id:</b>
  <%= @project.user_id %>

<br>
<%= link_to 'View all Employees', users_path %> 
</p>



&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<%= link_to 'Assign/Edit', edit_project_path(@project) %>&nbsp&nbsp |
&nbsp&nbsp<%= link_to 'Back', projects_path %>
</div>