testApp/config/routes.rb
TestApp::Application.routes.draw do 
  get "showallemp/index"
 
  devise_for :members,:controllers => { :sessions => "ses" }
   get "viewallemployees/index"
   get "showallemp/index"
  get "welcome/index"
  get "users/admins_welcome"
  resources :projects

  resources :users

   

  

	root :to => 'welcome#index'
	

end

testApp/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :DOB, :emp_id, :first_name, :gender, :hobbies, :interest, :last_name, :location, :project_id, :project_name
 validates :first_name, presence: true, length: { maximum: 20 }, :format => { :with => /^[A-Za-z]+$/ } 
validates :last_name, presence: true, length: { maximum: 20 },:format => { :with => /^[A-Za-z]+$/ }
validates :gender, presence: true

validates :interest, presence: true, length: { maximum: 40 }
validates :DOB, presence: true
validates :location, presence: true, length: { maximum: 40 },:format => { :with => /^[A-Za-z]+$/ }
validates :emp_id, presence: true, length: { maximum: 6 }


has_many :projects
belongs_to :member


end

testApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json

  def index
    @users = User.all
	@users = User.paginate page: params[:page], 
      per_page: 5
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

def admins_welcome

end

  # GET /users/1
  # GET /users/1.json
  def show
   @user = User.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end

  end

  # GET /users/new
  # GET /users/new.json
  def new

	@member = current_member
	@user = User.new
	@user.email = current_member.email

#render text: @user.email
	
=begin
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
      tag_ids = params[:tag_ids]
  end
=end
  
  end



  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    




    arr= params[:hobbies]
    hob=""
    if !(params[:hobbies]==nil)
          arr.each do |a|
    
            if(hob == "")
               hob=a
             else
               hob =hob +","+ a
            end
    end
    
    else
     @user.hobbies="none"
   
   end
    @user.hobbies=hob
    @user.gender=params[:gender]
     @user.project_name="none"                      # for not nil project value
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])




    arr= params[:hobbies]
    hob=""
    if !(params[:hobbies]==nil)
          arr.each do |a|
    
            if(hob == "")
               hob=a
             else
               hob =hob +","+ a
            end
    end
    
    else
     @user.hobbies="none"
   
   end
    @user.hobbies=hob
    @user.gender=params[:gender]
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

testApp/app/helpers/users_helper.rb
module UsersHelper
end

testApp/app/views/users/_admin_userview.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Dob</th>
    <th>Gender</th>
    <th>Location</th>
    <th>Project name</th>
    <th>Project</th>
    <th>Hobbies</th>
    <th>Interest</th>
    <th>Emp</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.DOB %></td>
    <td><%= user.gender %></td>
    <td><%= user.location %></td>
    <td><%= user.project_name %></td>
    <td><%= user.project_id %></td>
    <td><%= user.hobbies %></td>
    <td><%= user.interest %></td>
    <td><%= user.emp_id %></td>
    <td><%= link_to 'Show', user %></td>
    
  </tr>
<% end %>
</table>

testApp/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :DOB %><br />
    <%= f.date_select :DOB %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    

	<%= f.label :Male %><%= radio_button_tag 'gender', 'Male'%>
        <%= f.label :Female %><%=radio_button_tag 'gender', 'Female'%>

  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>

  <div class="field">
	Hobbies<br>
<% variable= Array["Singing","Dancing","Reading", "Swimming"] %>

     <% variable.each do |var| %>
         <%= var %>
	 <input type="checkbox" id= <%= var %> name= hobbies[] value= <%= var %> />
      <% end %>

  </div>
  <div class="field">
<br>
    <%= f.label :interest %><br />
    <%= f.text_field :interest %>
  </div>

 <div class="field">
<br>    <%= f.label :email %><br />
    <%= f.text_field :email, :readonly => :readonly %>
  </div>

  <div class="field">
 <br>   <%= f.label :emp_id %><br />
    <%= f.text_field :emp_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

testApp/app/views/users/_showingpro.html.erb
<% if projects.size >0 %>
<h1></h1>
<table>
  <tr>
    <th>Name</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% projects.each do |project|   %> <%#removed @from projects%>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.start_date %></td>
    <td><%= project.end_date %></td>
    <td><%= project.location %></td>
   <!-- <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  -->
</tr>
<% end %>

</table>

<% else %>
<h3>You have no project assigned.</h3>
<% end %>
<br />

<%=# link_to 'New Project', new_project_path
 %>

testApp/app/views/users/admin_userview.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Dob</th>
    <th>Gender</th>
    <th>Location</th>
    <th>Project name</th>
    <th>Project</th>
    <th>Hobbies</th>
    <th>Interest</th>
    <th>Emp</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.DOB %></td>
    <td><%= user.gender %></td>
    <td><%= user.location %></td>
    <td><%= user.project_name %></td>
    <td><%= user.project_id %></td>
    <td><%= user.hobbies %></td>
    <td><%= user.interest %></td>
    <td><%= user.emp_id %></td>

    
  </tr>
<% end %>
</table>

testApp/app/views/users/admins_welcome.html.erb
<div id="sidepanel">
<br><br>
<%= link_to "View Projects",projects_path %>
<br><br><hr>

<br>
<%= link_to "View User",users_path %>
</div>

<div id="content">
<h1>Welcome Admin</h1>

<h4>Use the tab and navigate to pages wher eyou can find the details of the projects. The projects can be viewed, edited and assigned to different employees.

<h4>You can also view the details of the employees. The same will inform you about the projects, the employee is handling.

</div>

testApp/app/views/users/edit.html.erb
<div id="sidepanel">
<%#= link_to "View Projects",projects_path %>

<%#= link_to "View User",users_path %>
</div>
<div id="content">

<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |


</div>

testApp/app/views/users/index.html.erb
<div id="sidepanel">
<br><br>
<%= link_to "View Projects",projects_path %>
<br><br><hr>

<br>
<%= link_to "View User",users_path %>
</div>
<div id="content">
<h1>Listing users</h1>

<table style="border:1px solid black">
  <tr>
    <th style="border-bottom: 1px solid black">First name</th><th></th>
    <th style="border-bottom: 1px solid black">Last name</th><th></th>
    <th style="border-bottom: 1px solid black">Dob</th><th></th>
    <th style="border-bottom: 1px solid black">Gender</th><th></th>
    <th style="border-bottom: 1px solid black">Location</th><th></th>
    <th style="border-bottom: 1px solid black">Project name</th><th></th>

 <!--   <th>Hobbies</th>
    <th>Interest</th> -->
    <th style="border-bottom: 1px solid black">Emp</th><th></th>
    <th style="border-bottom: 1px solid black">Email</th><th></th>
    <th></th><th></th>
   
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td><td> </td>
    <td><%= user.last_name %></td><td> </td>
    <td><%= user.DOB %></td><td> </td>
    <td><%= user.gender %></td><td> </td>
    <td><%= user.location %></td><td> </td>
    <td><%= user.project_name %></td><td> </td>
    
   <!-- <td><%= user.hobbies %></td>
    <td><%= user.interest %></td>-->
    <td><%= user.emp_id %></td><td> </td>
    <td><%= user.email %></td><td> </td>
    <td><%= link_to 'Show', user %></td><td> </td>
   <!-- <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
  </tr>
<% end %>
</table>

<br />

<!--<%= link_to 'Create New User', new_user_path %>-->

<%= will_paginate @users %></p> 
<link_to 'back' , user_path>
</div>

testApp/app/views/users/new.html.erb
<div id="sidepanel">

</div>
<div id="content">

<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

</div>

testApp/app/views/users/show.html.erb
<div id="sidepanel">

<% if (current_member.email=='admin@g.com') %>

<br><br>
<%= link_to "View Projects",projects_path %>
<br><br><hr>

<br>
<%= link_to "View User",users_path %>
<% end %>

</div>



<div id="content">

<% if (current_member.email!='admin@g.com') %>
<h1>Hello <%=  @user.first_name %></h1>
<% else %>
<h1> <%=  @user.first_name %>'s Details</h1>
<hr width=680px>
<% end %>





<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Dob:</b>
  <%= @user.DOB %>
</p>

<p>
  <b>Gender:</b>
  <%= @user.gender %>
</p>

<p>
  <b>Location:</b>
  <%= @user.location %>
</p>


<p>
  <b>Hobbies:</b>
  <%= @user.hobbies %>
</p>

<p>
  <b>Interest:</b>
  <%= @user.interest %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email%>
</p>

<p>
  <b>Emp:</b>
  <%= @user.emp_id %>
</p>


<h1 >Current projects</h1>
<%= render :partial=>"showingpro", :locals=>{:projects=>@user.projects} %>
<% if (current_member.email!='admin@g.com') %>
<%= link_to 'Edit', edit_user_path(@user) %>
<% else %>
<%= link_to 'Back', users_path %>
<% end %>

</div>